environment:
  matrix:
  - julia_version: 1.4
  - julia_version: 1.5

platform:
  - x86
  - x64

matrix:
  allow_failures:
  - julia_version: 1.4
  - julia_version: 1.5

branches:
  only:
    - master
    - dev
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%PYTHON%"
  - echo "%JL_BUILD_SCRIPT%"
  - cp C:\Users\appveyor\.julia\conda\3\Scripts\pip.exe C:\Users\appveyor\.julia\conda\3\Library\bin\pip.exe
  - cp C:\Users\appveyor\.julia\conda\3\Scripts\pip3.exe C:\Users\appveyor\.julia\conda\3\Library\bin\pip3.exe
  - cp C:\Users\appveyor\.julia\conda\3\Scripts\pip-script.py C:\Users\appveyor\.julia\conda\3\Library\bin\pip-script.py
  - cp C:\Users\appveyor\.julia\conda\3\Scripts\pip3-script.py C:\Users\appveyor\.julia\conda\3\Library\bin\pip3-script.py
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%PYTHON%"
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  
