environment:
  matrix:
  - julia_version: 1.4
  - julia_version: 1.5

platform:
  - x86
  - x64

matrix:
  allow_failures:
  - julia_version: 1.4
  - julia_version: 1.5

branches:
  only:
    - master
    - dev
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(\"PyCall\"); Pkg.build(\"PyCall\")"
  - if (Test-Path C:\Users\appveyor\pip) { ls C:\Users\appveyor\pip } else { echo C:\Users\appveyor\pip missing. }
  - if (Test-Path C:\Users\appveyor ) { ls C:\Users\appveyor } else { echo C:\Users\appveyor missing. }
  - if (Test-Path C:\Users\appveyor\.julia ) { ls C:\Users\appveyor\.julia } else { echo C:\Users\appveyor\.julia missing. }
  - echo "%PYTHON%"
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%PYTHON%"
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  
