environment:
  matrix:
  - julia_version: 1.4
  - julia_version: 1.5

platform:
  - x86
  - x64

matrix:
  allow_failures:
  - julia_version: 1.4
  - julia_version: 1.5

branches:
  only:
    - master
    - dev
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - SET PATH=C:\Python37;%PATH%
  - python get-pip.py --prefix=C:\Users\appveyor\.julia\conda\3\Library\tmp
  - ls C:\Users\appveyor\.julia\conda\3\Library\tmp
  - ls C:\Users\appveyor\.julia\conda\3\Library\tmp\Scripts
  - ls C:\Users\appveyor\.julia\conda\3\Library\tmp\Scripts\pip.exe
  - cp C:\Users\appveyor\.julia\conda\3\Library\tmp\Scripts\pip.exe C:\Users\appveyor\.julia\conda\3\Library\bin\pip.exe
  - ls C:\Users\appveyor\.julia\conda\3\Library\bin

build_script:
  - echo "%PYTHON%"
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%PYTHON%"
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  
